config/routes.rb
Rails.application.routes.draw do
  scope "admin/blog", :module => "breeze/blog", :name_prefix => "admin_blog" do
    root :to => "blogs#index"
    controller :blogs do
      post :setup_default
      put :switch
      get :settings
      put :settings
      get :new_spam_strategy
    end

    put "posts(.:format)" => "posts#mass_update"
    delete "posts(.:format)" => "posts#mass_destroy"
    resources :posts do
      collection do
        get :draft
        get :scheduled
        get :published
      end
    end
    put "comments(.:format)" => "comments#mass_update"
    delete "comments(.:format)" => "comments#mass_destroy"
    resources :comments do
      member do
        put :approve
        put :spam
      end
    end
    resources :categories do
      collection do
        put :reorder
      end
    end    
  end
end

app/models/breeze/blog.rb
module Breeze
  module Blog
    ARCHIVE_PART  = /(\d{4})(\/(\d{1,2})(\/(\d{1,2})(\/([^\/]+))?)?)?/.freeze unless defined?(ARCHIVE_PART)
    CATEGORY_PART = /category\/([^\/\.]+)/.freeze unless defined?(CATEGORY_PART)
    TAG_PART      = /tag\/([^\/\.]+)/.freeze unless defined?(TAG_PART)
    PREVIEW_PART  = /draft\/([^\/\.]+)/.freeze unless defined?(PREVIEW_PART)
    PERMALINK     = /(\/(#{ARCHIVE_PART}|#{CATEGORY_PART}|#{TAG_PART}|#{PREVIEW_PART}))?(\.\w+)?$/.freeze unless defined?(PERMALINK)
  end
end

app/models/breeze/blog/archive_view.rb
module Breeze
  module Blog
    class ArchiveView < IndexView
      attr_accessor :year, :month, :day
      
      def set_url_params(match)
        #self.year, self.month, self.day = [ 3, 5, 7 ].map { |i| match[i] && match[i].sub(/^0/, "").to_i }
      end
      
      def start_time
        #@start_time ||= if year
          #Time.zone.local(*[ year, month, day ].compact)
        #else
          #Time.zone.now
        #end
      end
      
      def end_time
        #start_time + if day
          #1.day
        #elsif month
          #1.month
        #else
          #1.year
        #end
      end
      
      def start_date
        #start_time.to_date
      end
      
      def end_date
        #end_time.to_date - 1.day
      end
      
      def posts
        super.where(
          :published_at => {
            '$gte' => start_time.utc,
            '$lt'  => end_time.utc
          }
        )
      end
    end
  end
end

app/models/breeze/blog/blog.rb
module Breeze
  module Blog
    class Blog < Breeze::Content::Page
      extend ActiveSupport::Memoizable

      field :posts_per_page, :type => Integer, :default => 5
      field :post_summary_length, :type => Integer, :default => 100
      field :comment_moderation, :type => Boolean, :default => false
      field :comment_notifications, :type => Boolean, :default => true
      has_many_related :posts, :class_name => "Breeze::Blog::Post"
      has_many_related :comments, :class_name => "Breeze::Blog::Comment"
      has_many_related :categories, :class_name => "Breeze::Blog::Category"
      embeds_one :spam_strategy, :class_name => "Breeze::Blog::Spam::Strategy"
      field :rss_title
      field :rss_description

      validates_associated :spam_strategy

      before_create :create_default_views
      before_create :create_default_spam_filtering
      after_destroy :destroy_posts_and_categories
      before_save :fix_post_permalinks

      def view_for(controller, request)
        if controller.admin_signed_in? && request.params[:view]
          returning views.by_name(request.params[:view]) do |view|
            view.with_url_params Breeze::Blog::PERMALINK.match(permalink)
          end
        else
          # permalink = request.path + request.params[:path]
          permalink = "/" + request.params[:path]
          view_from_permalink permalink
        end
      end

      def view_from_permalink(permalink)
        view = case permalink
        when "/blog"
          index_view
        when "/"
          index_view
        when /\/blog\/category\/.*$/
          category_view
        else
          post_view
        end
        view.with_url_params permalink
      end

      def method_missing(sym, *args, &block)
        if sym.to_s =~ /^(.+)_view$/
          view_name = $1
          views.detect { |v| v.name == view_name } ||
          views.build({ :name => view_name }, "Breeze::Blog::#{view_name.camelize}View".constantize)
        else
          super
        end
      end

      def self.find_by_permalink(permalink)
        post = Post.where(:permalink => permalink).first
        if post
          post.blog
        else
          category = Category.where(:permalink => permalink).first
          if category
            category.blog
          end
        end
      end

      def spam_strategy_attributes=(attrs)
        if attrs[:_type]
          klass = attrs[:_type].constantize
          self.spam_strategy = klass.new(attrs.except(:id, :_type))
        end
      end

      def rss_link
        permalink(:include_domain) + ".rss"
      end

    protected
      def create_default_views
        index_view
        archive_view
        category_view
        post_view
      end

      def create_default_spam_filtering
        self.spam_strategy = Breeze::Blog::Spam::NoStrategy.new
      end

      def destroy_posts_and_categories
        posts.destroy_all
        categories.destroy_all
      end

      def fix_post_permalinks
        if permalink_changed?
          # TODO: probably not the best idea to load them all at once
          posts.all.each do |post|
            post.blog = self # prevent loading from the database
            post.send :regenerate_permalink!
            post.save!
          end
        end
      end
    end
  end
end

app/models/breeze/blog/category.rb
module Breeze
  module Blog
    class Category
      include Mongoid::Document
      identity :type => String
      
      field :name
      field :position, :type => Integer
      belongs_to_related :blog, :class_name => "Breeze::Blog::Blog", :inverse_of => :categories
      include Breeze::Content::Mixins::Permalinks
      
      validates_presence_of :name, :slug
      validates_uniqueness_of :name, :slug, :scope => :blog_id
      before_validation :fill_in_slug
      after_destroy :remove_from_posts
      
      def to_s; name; end
      
      def regenerate_permalink!
        self.permalink = "#{blog.permalink}/categories/#{slug}"
      end
      
      def posts
        blog.posts.published.where :category_ids => id
      end
      
    protected
      def fill_in_slug
        if self.slug.blank? && self.name.present?
          self.slug = self.name.parameterize
          regenerate_permalink!
        end
      end
      
      def remove_from_posts
        Post.collection.update({ :blog_id => blog_id }, { "$pull" => { :category_ids => id } }, :multi => true)
      end
    end
  end
end

app/models/breeze/blog/category_view.rb
module Breeze
  module Blog
    class CategoryView < IndexView
      attr_accessor :permalink
      
      def set_url_params(permalink)
        super
        self.permalink = permalink
      end
            
      def category
        @category ||= blog.categories.where(:permalink => permalink).first
      end
      
      def posts
        super.where :category_id => category.try(:id)
      end
      
      def variables_for_render
        returning super do |vars|
          vars[:category] = category
        end
      end
    end
  end
end

app/models/breeze/blog/index_view.rb
module Breeze
  module Blog
    class IndexView < View

    end
  end
end

app/models/breeze/blog/post_view.rb
module Breeze
  module Blog
    class PostView < ArchiveView
      attr_accessor :permalink
      attr_accessor :comment
      attr_accessor :preview_only
      
      def set_url_params(permalink)
        super
        self.permalink = permalink
      end
      
      alias_method :preview_only?, :preview_only
      
      def posts
        (controller.admin_signed_in? ? blog.posts : blog.posts.published).where(:permalink => permalink)
      end
      
      def post
        @post ||= posts.first
      end

      def comment
        @comment ||= if controller.flash[:comment_id]
          blog.comments.find controller.flash[:comment_id]
        else
          nil
        end
      end
      
      def variables_for_render
        super.merge :post => post, :comments => post.present? ? post.comments.public : [], :comment => comment
      end
      
      def render!
        if request.post? && post.accepts_comments?
          @comment = post.comments.build(request.params[:comment])
          @comment.blog_id = blog.id
          if @comment.save
            controller.flash[:comment_id] = @comment.id
            controller.send :redirect_to, post.permalink
          else
            super
          end
        else
          super
        end
      end
    end
  end
end

app/models/breeze/blog/spam/no_strategy.rb
module Breeze
  module Blog
    module Spam
      class NoStrategy < Strategy
        def self.label
          "No automatic spam filtering"
        end
      end
    end
  end
end

app/models/breeze/blog/spam/strategy.rb
module Breeze
  module Blog
    module Spam
      class Strategy
        include Mongoid::Document
        identity :type => String

        embedded_in :blog, :class_name => "Breeze::Blog::Blog", :inverse_of => :spam_strategy
      
        def submit(comment)
          Breeze.queue comment, :deliver_notification!
        end
        
        def self.partial
          "/breeze/blog/blogs/spam/" + name.demodulize.underscore
        end
        
        def partial
          self.class.partial
        end
        
        def self.label
          name.demodulize.sub(/Strategy$/, "").underscore.humanize
        end
        
        def self.strategies
          @strategies ||= returning([]) do |classes|
            Dir[File.join(File.dirname(__FILE__), "*.rb")].each do |f|
              require f
            end
            subclasses.map(&:to_s).each do |k|
              classes << k
            end
          end
          @strategies.map &:constantize
        end
      end
    end
  end
end

app/controllers/breeze/admin/blog/blogs_controller.rb
module Breeze
  module Admin
    module Blog
      class BlogsController < Breeze::Admin::Blog::Controller
        def index
          @recent_comments = blog.comments.not_spam.most_recent(5)
        end
        
        def setup_default
          @blog = Breeze::Blog::Blog.new :title => "Blog", :parent_id => Breeze::Content::NavigationItem.root.first.try(:id)
          @blog.save!
          redirect_to admin_blog_root_path
        end
        
        def switch
          session[:blog_id] = params[:blog]
          redirect_to :action => "index"
        end
        
        def new_spam_strategy
          
        end
        
        def settings
          if request.put?
            if blog.update_attributes params[:blog]
              redirect_to admin_blog_settings_path
            else
              render :action => "settings"
            end
          end
        end
      end
    end
  end
end

app/controllers/breeze/admin/blog/categories_controller.rb
module Breeze
  module Admin
    module Blog
      class CategoriesController < Breeze::Admin::Blog::Controller
        before_filter :check_for_blogs
        
        def create
          @category = blog.categories.create params[:category]
        end
        
        def edit
          @category = blog.categories.find params[:id]
        end
        
        def update
          @category = blog.categories.find params[:id]
          @category.update_attributes params[:category]
        end
        
        def reorder
          params[:category].each_with_index do |category_id, i|
            blog.categories.find(category_id).update_attributes :position => i
          end
          render :nothing => true
        end
        
        def destroy
          @category = blog.categories.find params[:id]
          @category.try :destroy
        end
      end
    end
  end
end

app/controllers/breeze/admin/blog/comments_controller.rb
module Breeze
  module Admin
    module Blog
      class CommentsController < Breeze::Admin::Blog::Controller
        def index
          if request.xhr?
            @comments = blog.comments.send(params[:tab]).descending(:created_at).paginate(:page => params[:page] || 1)
            render :partial => "comments", :locals => { :comments => @comments }, :layout => false
          else
            @comments = blog.comments.descending(:created_at)
          end
        end
        
        def new
          @comment = new_comment
        end
        
        def create
          @comment = new_comment
          @comment.attributes = params[:comment]
          @comment.save
        end
        
        def approve
          comment.try :publish!
          render :action => :change
        end
        
        def spam
          comment.try :spam!
          render :action => :change
        end
        
        def mass_update
          @comments = blog.comments.find params[:comment_ids]
          @comments.each do |comment|
            comment.update_attributes params[:comment]
          end
        end
        
        def mass_destroy
          @comments = blog.comments.find params[:comment_ids]
          @comments.map &:destroy
        end
        
        def destroy
          comment.try :destroy
        end
        
      protected
        def comment
          @comment ||= blog.comments.find params[:id]
        end
        
        def new_comment
          if params[:comment] && params[:comment][:parent_id]
            Comment.reply_to blog.comments.find params[:comment][:parent_id], params[:comment]
          else
            blog.comments.build(params[:comment])
          end.with_author(current_user)
        end
      end
    end
  end
end

app/controllers/breeze/admin/blog/controller.rb
module Breeze
  module Admin
    module Blog
      class Controller < Breeze::Admin::AdminController
        helper Breeze::Blog::BlogAdminHelper
        helper Breeze::Blog::BlogHelper
        before_filter :check_for_blogs, :except => [ :setup_default ]

      protected
        def check_for_blogs
          unless blog
            render :action => "no_blog"
          end
        end

        def blog
          @blog ||= if session[:blog_id].present?
            Breeze::Blog::Blog.where(:_id => session[:blog_id]).first
          end || Breeze::Blog::Blog.first
          session[:blog_id] = @blog.try(:id)
          @blog
        end
        helper_method :blog
      end
    end
  end
end

app/controllers/breeze/admin/blog/posts_controller.rb
module Breeze
  module Admin
    module Blog
      class PostsController < Breeze::Admin::Blog::Controller
        def index
          @posts = blog.posts # TODO Order result set
        end
        
        def draft
          render :partial => "posts", :locals => { :posts => blog.posts.draft.paginate(:page => params[:page], :per_page => 10), :view => :draft }, :layout => false
        end
        
        def scheduled
          render :partial => "posts", :locals => { :posts => blog.posts.pending.paginate(:page => params[:page], :per_page => 10), :view => :pending }, :layout => false
        end
        
        def published
          render :partial => "posts", :locals => { :posts => blog.posts.published.paginate(:page => params[:page], :per_page => 10), :view => :published }, :layout => false
        end
        
        def show
          if (@post = blog.posts.find params[:id])
            redirect_to @post.permalink
          end
        end
        
        def new
          @post = blog.posts.build :author => current_user
        end
        
        def create
          @post = blog.posts.build params[:post]
          if @post.save
            redirect_to admin_blog_posts_path
          else
            render :action => "new"
          end
        end
        
        def edit
          @post = blog.posts.find params[:id]
        end
        
        def update
          @post = blog.posts.find params[:id]
          if @post.update_attributes(params[:post])
            flash[:notice] = "Your post was saved. <a href=\"#{@post.permalink}\">View your changes</a>, <a href=\"#{admin_blog_posts_path}\">return to the list of posts</a>, or close this message to continue editing."
            redirect_to edit_admin_blog_post_path(@post)
          else
            render :action => "edit"
          end
        end
        
        def destroy
          @post = blog.posts.find params[:id]
          @post.try :destroy
        end
        
        def mass_update
          @posts = blog.posts.find params[:post_ids]
          @posts.each do |post|
            post.update_attributes params[:post]
          end
        end
        
        def mass_destroy
          @posts = blog.posts.find params[:post_ids]
          @posts.map &:destroy
        end
        
      end
    end
  end
end

app/controllers/breeze/blog/blogs_controller.rb
module Breeze
  module Blog
    class BlogsController < Breeze::Blog::Controller
      def index
        @recent_comments = blog.comments.not_spam.most_recent(5)
      end
      
      def setup_default
        @blog = Blog.new :title => "Blog", :parent_id => Breeze::Content::NavigationItem.root.first.try(:id)
        @blog.save!
        redirect_to admin_blog_root_path
      end
      
      def switch
        session[:blog_id] = params[:blog]
        redirect_to :action => "index"
      end
      
      def new_spam_strategy
        
      end
      
      def settings
        if request.put?
          if blog.update_attributes params[:blog]
            redirect_to admin_blog_settings_path
          else
            render :action => "settings"
          end
        end
      end
    end
  end
end

app/views/breeze/admin/blog/posts/_form.html.erb
<%= pane_layout do |main| %>
	<%= main.inner do %>
		<%= breeze_form_for @post, :as => :post, :url => url do |form| %>
		  <%= scrollable_layout do %>
		    <h1><%= @post.new_record? ? 'New' : 'Edit' %> post</h1>
			  <%= render "/breeze/admin/shared/error_messages", :target => @post, :object_name => :post %>
		    <%= form.fieldset do %>
				  <%= form.text_field :title, :autocomplete => "off", :required => true %>
				  <%= form.text_field :slug, :required => true, :hint => "Forms part of the permalink URL for this post" %>
		      <%= form.select :author_id, Breeze::Admin::User.all.collect {|u| [ u.name, u._id ] }, :required => true %>
					<%= form.text_area :body, :required => true, :rows => 16, :class => "markup", :label => false %> 
		    <% end %>
		    
		    <%= form.fieldset :legend => "Summary", :id => "post_summary_fieldset", :class => "collapsible#{" collapsed" if @post.intro.blank?}" do %>
				  <%= form.text_area :intro, :label => false, :rows => 6, :class => "markup", :hint => "Enter a brief summary (about #{blog.post_summary_length} words) of your post, to be displayed on index, archive, and category pages" %> 
		    <% end %>
		  <% end %>

		  <%= fake_right_sidebar do %>
		    <%= scrollable_layout do %>
  		    <%= form.hidden_field :published_at, :value => "" %>
  		    <fieldset id="post_publishing">
            <%= check_box_tag :post_published, 1, !@post.draft? %>
            <%= form.fieldset :id => "post_publish_date", :style => "display: #{@post.draft? ? :none : :block}" do %>
              <li><%= text_field_tag :post_published_on, (@post.published_at || Time.now).strftime("%a %e %b, %Y") %></li>
              <%= form.time_select :published_at, :twelve_hour => true, :minute_step => 5, :label => false %>
              <%= content_tag :li, :class => "pending-message", :style => "display: #{@post.pending? ? :block : :none}" do %>
                This post has a ‘published’ date in the future. It won't be shown on your blog until that date: you can find it in the ‘scheduled’ tab of the posts list.
              <% end %>
            <% end %>
          </fieldset>

  			  <%= submit_tag "Save", :class => "large green save button" %>
  			  <%= link_to "View", @post.draft_permalink, :class => "large view button", :target => :_blank unless @post.new_record? %>
			  
  			  <%= hidden_field_tag "post[category_ids][]", "" %>
  			  <%= form.fieldset :legend => "Categories", :class => "post-categories" do %>
  			    <% blog.categories.ascending(:position).each do |category| %>
  			      <li><%= check_box_tag "post[category_ids][]", category.id, @post.categories.include?(category), :id => "post_category_ids_#{category.id}" %> <%= label_tag "post_category_ids_#{category.id}", category %></li>
  			    <% end %>
  			  <% end %>
			  
  			  <%= form.fieldset :legend => "Tags", :class => "post-tags" do %>
  			    <%= form.text_field :tags, :label => false, :value => form.object.tags.join(", "), :hint => "Press <strong>Return</strong> after each new tag".html_safe, :wrap => { :class => "tag-list" } %>
  			  <% end %>
  			<% end %>
		  <% end %>
		<% end %>
	<% end %>
<% end %>

<% content_for :left do %>
  <%= render :partial => "/breeze/admin/blog/blogs/left" %>
<% end %>

<% content_for :right do %>
  <%= pane_layout do |right| %>
    <% right.header do %>

    <% end %>
  <% end %>
<% end %>

<% content_for :head do %>
  <%= stylesheet_link_tag asset_path("breeze/marquess/marquess.css") %>
  <%= javascript_include_tag asset_path("breeze/marquess/marquess.js"), asset_path("breeze/blog.js") %>
<% end %>

<script type="text/javascript" charset="utf-8">
  var slug_updater = null;

  $(function() {
    $('#post_new #post_title').live('input', function() {
      $('#post_slug').each(function() {
        if (!this.updated) {
          $(this).val($('#post_title').val().toLowerCase().replace(/[^a-z0-9\-]+/g, '-'));
        }
      });
    });
    $('#post_slug').live('input', function() {
      this.updated = true;
    });

    $('.post-categories li').live('click', function(e) {
      if ($(event.target).is('li')) {
        $(this).find(':input').each(function() { this.checked = !this.checked; });
      }
    });
    
    $('textarea.markup').marquess();
    $('#post_published_on').datepicker({
      dateFormat: 'D d M, yy'
    }).change(function() {
      var new_date = $.datepicker.parseDate('D d M, yy', $(this).val());
      $('#post_published_at_1i').val(new_date.getFullYear());
      $('#post_published_at_2i').val(new_date.getMonth() + 1);
      $('#post_published_at_3i').val(new_date.getDate());
      new_date.setHours(parseInt($('#post_published_at_4i').val()));
      new_date.setMinutes(parseInt($('#post_published_at_5i').val()));
      $('#post_publish_date .pending-message').toggle(new_date > new Date());
    });
    
    $('#post_published').change(function() {
      var published = $('#post_published:checked').length > 0;
      $('#post_publish_date').toggle(published).find(':input').attr('disabled', !published);
    }).change().hide();
    $('<div class="publish-toggle"></div>').insertAfter('#post_published').css({
      'background-position': ($('#post_published:checked').length > 0 ? 0 : 100) + '% 0%'
    }).mousedown(function() {
      $('#post_published').click().change();
      $(this).animate({
        'background-position': ($('#post_published:checked').length > 0 ? 0 : 100) + '% 0%'
      }, 'slow', 'easeInOutQuad')
    });
    
    $('#post_new, #post_edit').live('submit', function() {
      $('.textboxlist-bit-editable-input', this).each(function() {
        if ($(this).val() != '') {
          this.focus();
          e = jQuery.Event("keydown");
          e.which = 13;
          $(this).trigger(e);
        }
      });
    });
    
    $('#post_published_at_5i').after('<small class="am">am</small><small class="pm">pm</small>');
    $('#post_published_at_4i').change(function() {
      var h = parseInt($(this).val());
      $(this).parent().find('.am').toggle(h < 12);
      $(this).parent().find('.pm').toggle(h >= 12);
    }).change().find('option').each(function() {
      $(this).text($(this).text().replace(/ [AP]M$/i, ''));
    });
    
    new $.TextboxList('#post_tags', { });
    
    $('#post_summary_fieldset.collapsed').find('ol.form').hide();
    $('#post_summary_fieldset legend').click(function() {
      var fieldset = $(this).parent()
      fieldset.toggleClass('collapsed').find('ol.form').toggle(!fieldset.hasClass('collapsed'));
    });
        
    $('#post_new :input, #post_edit :input').live('change input', function() {
      window.unsaved_changes = true;
    });
    window.unsaved_changes = false;
    window.onbeforeunload = function() {
      if (window.unsaved_changes) {
        return 'If you continue, you will lose your unsaved changes. Do you want to proceed anyway?';
      }
    };
    $('.save.button').click(function() {
      window.unsaved_changes = false;
      return true;
    });
  });
</script>

app/views/breeze/admin/blog/posts/edit.html.erb
<% content_for :title, "Edit post" %>
<%= render "breeze/admin/blog/posts/form", :url => admin_blog_post_path(@post) %>

app/views/breeze/admin/blog/posts/index.html.erb
<% content_for :title, "Blog posts" %>

<%= tabbed_layout do |tabs| %>
	<% tabs.header do %>
	  <%= link_to "New blog post", new_admin_blog_post_path, :class => "large new blog_post button" %>
	<% end %>
  <% tabs.draft :title => "Drafts <small>#{@posts.draft.size}</small>".html_safe do %>
    <%= scrollable_layout do %>
      <h2>Draft posts</h2>
      <p>These posts are not yet ready to be displayed on your blog.</p>
      <%= render :partial => "breeze/admin/blog/posts/posts", :locals => { :posts => @posts.draft.paginate(:page => params[:draft_page], :per_page => 10), :view => :draft } %>
    <% end %>
  <% end %>
  <% tabs.pending :title => "Scheduled <small>#{@posts.pending.size}</small>".html_safe do %>
    <%= scrollable_layout do %>
      <h2>Scheduled posts</h2>
      <p>These posts are ready to be displayed on your blog, but are awaiting their publication date.</p>
      <%= render :partial => "breeze/admin/blog/posts/posts", :locals => { :posts => @posts.pending.paginate(:page => params[:pending_page], :per_page => 10), :view => :pending } %>
    <% end %>
  <% end %>
  <% tabs.published :title => "Published <small>#{@posts.published.size}</small>".html_safe do %>
    <%= scrollable_layout do %>
      <h2>Published posts</h2>
      <p>These posts are available on your blog.</p>
      <%= render :partial => "breeze/admin/blog/posts/posts", :locals => { :posts => @posts.published.paginate(:page => params[:published_page], :per_page => 10), :view => :published } %>
    <% end %>
  <% end %>
<% end %>

<% content_for :left do %>
  <%= render :partial => "breeze/admin/blog/blogs/left" %>
<% end %>

<script type="text/javascript" charset="utf-8">
  function makeDraggable(posts) {
    $(posts).not('.ui-draggable').draggable({
      appendTo: '#main',
      cursor: 'default',
      cursorAt: { left: -8, top: -8 },
      helper: function() {
        return $('<div class="comment-drag-helper">1</div>');
      },
      start: function(event, ui) {
        if ($(':checked', this).length > 0) {
          $(ui.helper).html($(this).closest('tbody').find(':checked').length);
        }
      }
    });
  }

  $(function() {
    makeDraggable('.posts-container .post');

    $('.posts-container tfoot .pagination a').live('click', function() {
      var container = $(this).closest('.container');
      var tab = $(this).closest('.tab-pane').attr('id').replace(/^tab_/, '');
      $.get(this.href, function(data) {
        container.replaceWith(data);
        makeDraggable('.posts-container:visible .post');
      });
      return false;
    });
    
    $('#main-tabs-tabs li:not(.active) a').not('[href=#tab_pending]').droppable({
      accept: '.post',
      hoverClass: 'drop-hover',
      tolerance: 'pointer',
      drop: function(e, ui) {
        var post_ids = [];
        var posts;
        if ($(':checked', ui.draggable).length > 0) {
          posts = $(ui.draggable).closest('table').find('tbody :checked').closest('.post');
        } else {
          posts = $(ui.draggable);
        }        
        posts.each(function() {
          post_ids.push(this.id.replace(/^post_/, 'post_ids[]='));
        });
        posts.fadeOut(function() { $(this).remove(); });
        $.ajax({
          url: '/admin/blog/posts.js',
          type: 'post',
          dataType: 'script',
          data: '_method=put&' + post_ids.join('&') + '&post[status]=' + $(this).attr('href').replace(/^.*\#tab_/, '')
        });
      }
    });
    
    $('.posts-container thead :checkbox').live('change', function() {
      var posts = $('tbody :checkbox', $(this).closest('table'));
      if (this.checked) {
        posts.attr('checked', true);
      } else {
        posts.removeAttr('checked');
      }
    });
    
    $('.posts-container :checkbox').live('change', function() {
      var container = $(this).closest('.container');
      $('.with-selected', container).toggle($('tbody :checked', container).length > 0);
    });
    
    $('.posts-container .with-selected .button.not(.delete)').live('click', function() {
      var post_ids = [];
      var posts = $(this).closest('.container').find('tbody :checked').closest('.post');
      posts.each(function() { post_ids.push(this.id.replace(/^post_/, 'post_ids[]=')); });
      var method = $(this).is('.delete') ? 'delete' : 'put';
      var data = '_method=' + method + '&' + post_ids.join('&');
      if ($(this).is('.publish')) { data += '&post[status]=publish'; }
      if ($(this).is('.unpublish')) { data += '&post[status]=draft'; }
      $.ajax({
        url:'/admin/blog/posts.js',
        type:'post',
        dataType:'script',
        data: data
      });
      $(this).closest('.container').find('thead :checked').removeAttr('checked');
      $(this).closest('.with-selected').hide();
      return false;
    });

    $('.posts-container .with-selected .delete').live('click', function() {
      var button = this;
      var post_ids = [];
      var posts = $(this).closest('.container').find('tbody :checked').closest('.post');
      posts.each(function() { post_ids.push(this.id.replace(/^post_/, 'post_ids[]=')); });
      
      $('<p>Really delete these posts?</p>').dialog({
        title:'Confirm delete',
        modal: true,
        resizable: false,
        buttons: {
          Delete: function() {
            $(this).dialog('close');
            $.ajax({
              url:'/admin/blog/posts.js',
              type:'post',
              dataType:'script',
              data: '_method=delete&' + post_ids.join('&')
            });
            $(button).closest('.container').find('thead :checked').removeAttr('checked');
            $(button).closest('.with-selected').hide();
          },
          Cancel: function() {
            $(this).dialog('close');
          }
        },
        close: function() { $(this).remove(); }
      });
      return false;
    });
  });
</script>

app/views/breeze/admin/blog/posts/new.html.erb
<% content_for :title, "New post" %>
<%= render "breeze/admin/blog/posts/form", :url => admin_blog_posts_path %>