config/routes.rb
Rails.application.routes.draw do
  scope "admin/blog", :module => "breeze/blog", :name_prefix => "admin_blog" do
    root :to => "blogs#index"
    controller :blogs do
      post :setup_default
      put :switch
      get :settings
      put :settings
      get :new_spam_strategy
    end

    put "posts(.:format)" => "posts#mass_update"
    delete "posts(.:format)" => "posts#mass_destroy"
    resources :posts do
      collection do
        get :draft
        get :scheduled
        get :published
      end
    end
    put "comments(.:format)" => "comments#mass_update"
    delete "comments(.:format)" => "comments#mass_destroy"
    resources :comments do
      member do
        put :approve
        put :spam
      end
    end
    resources :categories do
      collection do
        put :reorder
      end
    end    
  end
end

app/models/breeze/blog.rb
module Breeze
  module Blog
    ARCHIVE_PART  = /(\d{4})(\/(\d{1,2})(\/(\d{1,2})(\/([^\/]+))?)?)?/.freeze unless defined?(ARCHIVE_PART)
    CATEGORY_PART = /category\/([^\/\.]+)/.freeze unless defined?(CATEGORY_PART)
    TAG_PART      = /tag\/([^\/\.]+)/.freeze unless defined?(TAG_PART)
    PREVIEW_PART  = /draft\/([^\/\.]+)/.freeze unless defined?(PREVIEW_PART)
    PERMALINK     = /(\/(#{ARCHIVE_PART}|#{CATEGORY_PART}|#{TAG_PART}|#{PREVIEW_PART}))?(\.\w+)?$/.freeze unless defined?(PERMALINK)
  end
end

app/models/breeze/blog/archive_view.rb
module Breeze
  module Blog
    class ArchiveView < IndexView
      attr_accessor :year, :month, :day
      
      def set_url_params(match)
        #self.year, self.month, self.day = [ 3, 5, 7 ].map { |i| match[i] && match[i].sub(/^0/, "").to_i }
      end
      
      def start_time
        #@start_time ||= if year
          #Time.zone.local(*[ year, month, day ].compact)
        #else
          #Time.zone.now
        #end
      end
      
      def end_time
        #start_time + if day
          #1.day
        #elsif month
          #1.month
        #else
          #1.year
        #end
      end
      
      def start_date
        #start_time.to_date
      end
      
      def end_date
        #end_time.to_date - 1.day
      end
      
      def posts
        super.where(
          :published_at => {
            '$gte' => start_time.utc,
            '$lt'  => end_time.utc
          }
        )
      end
    end
  end
end

app/models/breeze/blog/blog.rb
module Breeze
  module Blog
    class Blog < Breeze::Content::Page
      extend ActiveSupport::Memoizable

      field :posts_per_page, :type => Integer, :default => 5
      field :post_summary_length, :type => Integer, :default => 100
      field :comment_moderation, :type => Boolean, :default => false
      field :comment_notifications, :type => Boolean, :default => true
      has_many_related :posts, :class_name => "Breeze::Blog::Post"
      has_many_related :comments, :class_name => "Breeze::Blog::Comment"
      has_many_related :categories, :class_name => "Breeze::Blog::Category"
      embeds_one :spam_strategy, :class_name => "Breeze::Blog::Spam::Strategy"
      field :rss_title
      field :rss_description

      validates_associated :spam_strategy

      before_create :create_default_views
      before_create :create_default_spam_filtering
      after_destroy :destroy_posts_and_categories
      before_save :fix_post_permalinks

      def view_for(controller, request)
        if controller.admin_signed_in? && request.params[:view]
          returning views.by_name(request.params[:view]) do |view|
            view.with_url_params Breeze::Blog::PERMALINK.match(permalink)
          end
        else
          # permalink = request.path + request.params[:path]
          permalink = "/" + request.params[:path]
          view_from_permalink permalink
        end
      end

      def view_from_permalink(permalink)
        view = case permalink
        when "/blog"
          index_view
        when "/"
          index_view
        when /\/blog\/category\/.*$/
          category_view
        else
          post_view
        end
        view.with_url_params permalink
      end

      def method_missing(sym, *args, &block)
        if sym.to_s =~ /^(.+)_view$/
          view_name = $1
          views.detect { |v| v.name == view_name } ||
          views.build({ :name => view_name }, "Breeze::Blog::#{view_name.camelize}View".constantize)
        else
          super
        end
      end

      def self.find_by_permalink(permalink)
        post = Post.where(:permalink => permalink).first
        if post
          post.blog
        else
          category = Category.where(:permalink => permalink).first
          if category
            category.blog
          end
        end
      end

      def spam_strategy_attributes=(attrs)
        if attrs[:_type]
          klass = attrs[:_type].constantize
          self.spam_strategy = klass.new(attrs.except(:id, :_type))
        end
      end

      def rss_link
        permalink(:include_domain) + ".rss"
      end

    protected
      def create_default_views
        index_view
        archive_view
        category_view
        post_view
      end

      def create_default_spam_filtering
        self.spam_strategy = Breeze::Blog::Spam::NoStrategy.new
      end

      def destroy_posts_and_categories
        posts.destroy_all
        categories.destroy_all
      end

      def fix_post_permalinks
        if permalink_changed?
          # TODO: probably not the best idea to load them all at once
          posts.all.each do |post|
            post.blog = self # prevent loading from the database
            post.send :regenerate_permalink!
            post.save!
          end
        end
      end
    end
  end
end

app/models/breeze/blog/category.rb
module Breeze
  module Blog
    class Category
      include Mongoid::Document
      identity :type => String
      
      field :name
      field :position, :type => Integer
      belongs_to_related :blog, :class_name => "Breeze::Blog::Blog", :inverse_of => :categories
      include Breeze::Content::Mixins::Permalinks
      
      validates_presence_of :name, :slug
      validates_uniqueness_of :name, :slug, :scope => :blog_id
      before_validation :fill_in_slug
      after_destroy :remove_from_posts
      
      def to_s; name; end
      
      def regenerate_permalink!
        self.permalink = "#{blog.permalink}/categories/#{slug}"
      end
      
      def posts
        blog.posts.published.where :category_ids => id
      end
      
    protected
      def fill_in_slug
        if self.slug.blank? && self.name.present?
          self.slug = self.name.parameterize
          regenerate_permalink!
        end
      end
      
      def remove_from_posts
        Post.collection.update({ :blog_id => blog_id }, { "$pull" => { :category_ids => id } }, :multi => true)
      end
    end
  end
end

app/models/breeze/blog/category_view.rb
module Breeze
  module Blog
    class CategoryView < IndexView
      attr_accessor :permalink
      
      def set_url_params(permalink)
        super
        self.permalink = permalink
      end
            
      def category
        @category ||= blog.categories.where(:permalink => permalink).first
      end
      
      def posts
        super.where :category_id => category.try(:id)
      end
      
      def variables_for_render
        returning super do |vars|
          vars[:category] = category
        end
      end
    end
  end
end

app/models/breeze/blog/index_view.rb
module Breeze
  module Blog
    class IndexView < View

    end
  end
end

app/models/breeze/blog/post_view.rb
module Breeze
  module Blog
    class PostView < ArchiveView
      attr_accessor :permalink
      attr_accessor :comment
      attr_accessor :preview_only
      
      def set_url_params(permalink)
        super
        self.permalink = permalink
      end
      
      alias_method :preview_only?, :preview_only
      
      def posts
        (controller.admin_signed_in? ? blog.posts : blog.posts.published).where(:permalink => permalink)
      end
      
      def post
        @post ||= posts.first
      end

      def comment
        @comment ||= if controller.flash[:comment_id]
          blog.comments.find controller.flash[:comment_id]
        else
          nil
        end
      end
      
      def variables_for_render
        super.merge :post => post, :comments => post.present? ? post.comments.public : [], :comment => comment
      end
      
      def render!
        if request.post? && post.accepts_comments?
          @comment = post.comments.build(request.params[:comment])
          @comment.blog_id = blog.id
          if @comment.save
            controller.flash[:comment_id] = @comment.id
            controller.send :redirect_to, post.permalink
          else
            super
          end
        else
          super
        end
      end
    end
  end
end

app/models/breeze/blog/spam/no_strategy.rb
module Breeze
  module Blog
    module Spam
      class NoStrategy < Strategy
        def self.label
          "No automatic spam filtering"
        end
      end
    end
  end
end

app/models/breeze/blog/spam/strategy.rb
module Breeze
  module Blog
    module Spam
      class Strategy
        include Mongoid::Document
        identity :type => String

        embedded_in :blog, :class_name => "Breeze::Blog::Blog", :inverse_of => :spam_strategy
      
        def submit(comment)
          Breeze.queue comment, :deliver_notification!
        end
        
        def self.partial
          "/breeze/blog/blogs/spam/" + name.demodulize.underscore
        end
        
        def partial
          self.class.partial
        end
        
        def self.label
          name.demodulize.sub(/Strategy$/, "").underscore.humanize
        end
        
        def self.strategies
          @strategies ||= returning([]) do |classes|
            Dir[File.join(File.dirname(__FILE__), "*.rb")].each do |f|
              require f
            end
            subclasses.map(&:to_s).each do |k|
              classes << k
            end
          end
          @strategies.map &:constantize
        end
      end
    end
  end
end

app/controllers/breeze/admin/blog/blogs_controller.rb
module Breeze
  module Admin
    module Blog
      class BlogsController < Breeze::Admin::Blog::Controller
        def index
          @recent_comments = blog.comments.not_spam.most_recent(5)
        end
        
        def setup_default
          @blog = Breeze::Blog::Blog.new :title => "Blog", :parent_id => Breeze::Content::NavigationItem.root.first.try(:id)
          @blog.save!
          redirect_to admin_blog_root_path
        end
        
        def switch
          session[:blog_id] = params[:blog]
          redirect_to :action => "index"
        end
        
        def new_spam_strategy
          
        end
        
        def settings
          if request.put?
            if blog.update_attributes params[:blog]
              redirect_to admin_blog_settings_path
            else
              render :action => "settings"
            end
          end
        end
      end
    end
  end
end

app/controllers/breeze/admin/blog/categories_controller.rb
module Breeze
  module Admin
    module Blog
      class CategoriesController < Breeze::Admin::Blog::Controller
        before_filter :check_for_blogs
        
        def create
          @category = blog.categories.create params[:category]
        end
        
        def edit
          @category = blog.categories.find params[:id]
        end
        
        def update
          @category = blog.categories.find params[:id]
          @category.update_attributes params[:category]
        end
        
        def reorder
          params[:category].each_with_index do |category_id, i|
            blog.categories.find(category_id).update_attributes :position => i
          end
          render :nothing => true
        end
        
        def destroy
          @category = blog.categories.find params[:id]
          @category.try :destroy
        end
      end
    end
  end
end

app/controllers/breeze/admin/blog/comments_controller.rb
module Breeze
  module Admin
    module Blog
      class CommentsController < Breeze::Admin::Blog::Controller
        def index
          if request.xhr?
            @comments = blog.comments.send(params[:tab]).descending(:created_at).paginate(:page => params[:page] || 1)
            render :partial => "comments", :locals => { :comments => @comments }, :layout => false
          else
            @comments = blog.comments.descending(:created_at)
          end
        end
        
        def new
          @comment = new_comment
        end
        
        def create
          @comment = new_comment
          @comment.attributes = params[:comment]
          @comment.save
        end
        
        def approve
          comment.try :publish!
          render :action => :change
        end
        
        def spam
          comment.try :spam!
          render :action => :change
        end
        
        def mass_update
          @comments = blog.comments.find params[:comment_ids]
          @comments.each do |comment|
            comment.update_attributes params[:comment]
          end
        end
        
        def mass_destroy
          @comments = blog.comments.find params[:comment_ids]
          @comments.map &:destroy
        end
        
        def destroy
          comment.try :destroy
        end
        
      protected
        def comment
          @comment ||= blog.comments.find params[:id]
        end
        
        def new_comment
          if params[:comment] && params[:comment][:parent_id]
            Comment.reply_to blog.comments.find params[:comment][:parent_id], params[:comment]
          else
            blog.comments.build(params[:comment])
          end.with_author(current_user)
        end
      end
    end
  end
end

app/controllers/breeze/admin/blog/controller.rb
module Breeze
  module Admin
    module Blog
      class Controller < Breeze::Admin::AdminController
        helper Breeze::Blog::BlogAdminHelper
        helper Breeze::Blog::BlogHelper
        before_filter :check_for_blogs, :except => [ :setup_default ]

      protected
        def check_for_blogs
          unless blog
            render :action => "no_blog"
          end
        end

        def blog
          @blog ||= if session[:blog_id].present?
            Breeze::Blog::Blog.where(:_id => session[:blog_id]).first
          end || Breeze::Blog::Blog.first
          session[:blog_id] = @blog.try(:id)
          @blog
        end
        helper_method :blog
      end
    end
  end
end

app/controllers/breeze/admin/blog/posts_controller.rb
module Breeze
  module Admin
    module Blog
      class PostsController < Breeze::Admin::Blog::Controller
        def index
          @posts = blog.posts # TODO Order result set
        end
        
        def draft
          render :partial => "posts", :locals => { :posts => blog.posts.draft.paginate(:page => params[:page], :per_page => 10), :view => :draft }, :layout => false
        end
        
        def scheduled
          render :partial => "posts", :locals => { :posts => blog.posts.pending.paginate(:page => params[:page], :per_page => 10), :view => :pending }, :layout => false
        end
        
        def published
          render :partial => "posts", :locals => { :posts => blog.posts.published.paginate(:page => params[:page], :per_page => 10), :view => :published }, :layout => false
        end
        
        def show
          if (@post = blog.posts.find params[:id])
            redirect_to @post.permalink
          end
        end
        
        def new
          @post = blog.posts.build :author => current_user
        end
        
        def create
          @post = blog.posts.build params[:post]
          if @post.save
            redirect_to admin_blog_posts_path
          else
            render :action => "new"
          end
        end
        
        def edit
          @post = blog.posts.find params[:id]
        end
        
        def update
          @post = blog.posts.find params[:id]
          if @post.update_attributes(params[:post])
            flash[:notice] = "Your post was saved. <a href=\"#{@post.permalink}\">View your changes</a>, <a href=\"#{admin_blog_posts_path}\">return to the list of posts</a>, or close this message to continue editing."
            redirect_to edit_admin_blog_post_path(@post)
          else
            render :action => "edit"
          end
        end
        
        def destroy
          @post = blog.posts.find params[:id]
          @post.try :destroy
        end
        
        def mass_update
          @posts = blog.posts.find params[:post_ids]
          @posts.each do |post|
            post.update_attributes params[:post]
          end
        end
        
        def mass_destroy
          @posts = blog.posts.find params[:post_ids]
          @posts.map &:destroy
        end
        
      end
    end
  end
end

app/controllers/breeze/blog/blogs_controller.rb
module Breeze
  module Blog
    class BlogsController < Breeze::Blog::Controller
      def index
        @recent_comments = blog.comments.not_spam.most_recent(5)
      end
      
      def setup_default
        @blog = Blog.new :title => "Blog", :parent_id => Breeze::Content::NavigationItem.root.first.try(:id)
        @blog.save!
        redirect_to admin_blog_root_path
      end
      
      def switch
        session[:blog_id] = params[:blog]
        redirect_to :action => "index"
      end
      
      def new_spam_strategy
        
      end
      
      def settings
        if request.put?
          if blog.update_attributes params[:blog]
            redirect_to admin_blog_settings_path
          else
            render :action => "settings"
          end
        end
      end
    end
  end
end

app/views/breeze/blog/blogs/_comment.html.erb
<%= content_tag :div, :class => :comment, :id => "comment_#{comment.id}" do %>
  <p class="comment-author"><strong><%= link_to_unless comment.website.blank?, comment.name, comment.website %></strong> on <%= link_to comment.post.title, comment.post.permalink %></p>
  <%= image_tag comment.gravatar(:size => 32), :class => :gravatar %>
  <%= content_tag :div, comment.body, :class => "comment-body" %>
  <p class="comment-actions">
    <%= link_to "Approve", approve_admin_blog_comment_path(comment), :remote => true, :method => :put, :class => "small green approve button" unless comment.published? %>
    <%= link_to "Spam", spam_admin_blog_comment_path(comment), :remote => true, :method => :put, :class => "small black spam button" unless comment.spam? %>
    <%= link_to "Delete", admin_blog_comment_path(comment), :remote => true, :method => :delete, :class => "small red delete button" %>
    <%= link_to "Reply", new_admin_blog_comment_path(:comment => { :parent_id => comment.id }), :class => "small black reply button" if comment.published? %>
  </p>
<% end %>

app/views/breeze/blog/blogs/_left.html.erb
<%= pane_layout do |left| %>
  <% left.header do %>
    <%= blog_switcher %>
  <% end %>
  <% left.inner do %>
    <%= blog_menu %>
  <% end %>
<% end %>
<% content_for :head do %>
  <%= stylesheet_link_tag "/breeze/stylesheets/blog.css" %>
<% end %>

app/views/breeze/blog/blogs/_post.html.erb
<tr>
  <td><%= check_box_tag "post_ids[]", post.id %></td>
  <td class="title">
    <%= link_to post.title, edit_blog_admin_post_path(post), :class => "title-link" %>
    <p class="categories"><%#= post.categories.empty? ? "(none)" : post.categories.map(&:to_s).join(", ") %></p>
    <p class="post-controls">
      <%#= link_to "View", post.permalink, :target => :_blank %> |
      <%= link_to "Edit", edit_blog_admin_post_path(post) %> |
      <%#= link_to "Delete", confirm_delete_blog_post_path(post), :rel => :facebox %>
    </p>
  </td>
  <td class="author"><%= post.author.name %></td>
  <td class="tags"><%#= post.tags.empty? ? "(no tags)" : post.tags.join(", ") %></td>
  <td class="comments"><%#= post.comments_count || 0 %></td>
  <td class="date"><%= (post.published_at || post.updated_at).to_date.to_formatted_s(:rfc822) %><br /><small><%= post.published? ? "(Published)" : "(Edited)" %></small></td>
</tr>

app/views/breeze/blog/blogs/_posts.html.erb
<%# form_tag posts_blog_path do -%>
  <div id="<%= view %>-posts" class="posts-container container">
    <%= hidden_field_tag :mode, nil, :id => "#{view}_mode" %>
    <%= hidden_field_tag :view, view, :id => "#{view}_view" %>
    <div class="table-tasks-popup">
      <p>
        <%#= link_to "Delete selected", "#", :class => "delete-selected-posts", :rel => :delete %>
      </p>
    </div>
    <table class="fancy posts">
      <thead>
        <tr>
          <th class="first" style="width:5%;"><input class="checkbox select-all" type="checkbox" /></th>
          <th style="width:35%;">Post</th>
          <th style="width:15%;">Author</th>
          <th style="width:20%;">Tags</th>
          <th style="width:10%;">Comments</th>
          <th class="last" style="width:15%;">Date</th>
        </tr>
      </thead>
      <tbody>
        <% if @posts.empty? -%>
          <tr><td class="empty" colspan="7">There are no <%= view %> posts to show here.</td></tr>
        <% else -%>
          <%= render :partial => "post", :collection => posts %>
        <% end -%>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="7"><%#= will_paginate @posts, :param_name => :"_page" %>&nbsp;</td>
        </tr>
      </tfoot>
    </table>
  </div>
<%# end -%>

app/views/breeze/blog/blogs/_switcher.html.erb
<div id="blog-switcher">
  <%= form_tag admin_blog_switch_path, :method => :put do %>
    <label>Blog:</label>
    <%= select_tag :blog, options_for_select(blogs.collect { |b| [ b.title, b.id ] }, blog.id) %>
  <% end %>
</div>
<script type="text/javascript" charset="utf-8">
  $(function() {
    $('#blog-switcher select').change(function() {
      $(this).closest('form').eq(0).each(function() { this.submit(); });
    });
  });
</script>

app/views/breeze/blog/blogs/index.html.erb
<% content_for :title, "Blog" %>

<% pane_layout do |panes| %>
  <% panes.header do %>
    <%= link_to "New blog post", new_admin_blog_post_path, :class => "large new blog_post button" %>
  <% end -%>
  <% panes.inner do %>
    <%= scrollable_layout do %>
      <div id="blog_dashboard">
        <div id="posts" class="box col3">
          <h2>Your posts</h2>
          <table class="at-a-glance">
            <%= at_a_glance blog.posts.published.count, "public post(s)", admin_blog_posts_path + "#tab_published" %>
            <%= at_a_glance blog.posts.scheduled.count, "post(s) scheduled for publication", admin_blog_posts_path + "#tab_pending" %>
            <%= at_a_glance blog.posts.draft.count, "draft(s)", admin_blog_posts_path + "#tab_draft" %>
            <%= at_a_glance blog.categories.count, "category(s)", admin_blog_settings_path + "#tab_categories" %>
          </table>
          <p><%= last_published(blog) %></p>
        </div>

        <div id="comments" class="box col3">
          <h2>Your comments</h2>
          <table class="at-a-glance">
            <%= at_a_glance blog.comments.awaiting_reply.count, "comment(s) awaiting_reply", admin_blog_comments_path + "#tab_awaiting_reply" %>
            <%= at_a_glance blog.comments.published.count, "approved comment(s)", admin_blog_comments_path + "#tab_published" %>
            <%= at_a_glance blog.comments.pending.count, "comment(s) awaiting moderation", admin_blog_comments_path + "#tab_pending" %>
            <%= at_a_glance blog.comments.spam.count, "comment(s) marked as spam", admin_blog_comments_path + "#tab_spam" %>
          </table>
          <p>Replying to comments encourages discussion by letting your visitors know you read and value their contributions.</p>
        </div>

        <div id="recent-comments" class="box col3">
          <h2>Recent comments</h2>
          <% if @recent_comments.any? %>
            <%= render :partial => "comment", :collection => @recent_comments %>
            <p><%= link_to "More comments", admin_blog_comments_path %></p>
          <% else %>
            <p>You have no recent comments</p>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% panes.footer do %>

  <% end %>
<% end %>

<% content_for :left do %>
  <%= render :partial => "left" %>
<% end %>

<% content_for :head do %>
  <%= javascript_include_tag "/breeze/javascripts/masonry.js" %>
<% end %>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $('#blog_dashboard').masonry({
      columnWidth: 128,
      itemSelector: '.box',
      animate: true,
      animationOptions: {
        duration: 200,
        easing: 'easeOutCubic'
      }
    });

    $('#recent-comments .comment .reply').live('click', function() {
      $.get(this.href, function(data) {
        $('<div></div>').html(data).dialog({
          title: 'Reply to comment',
          modal: true,
          width: 512,
          resizable: false,
          open: function() {
            $('textarea', this)[0].focus();
          },
          close: function() {
            $(this).remove();
          },
          buttons: {
            Cancel: function() { $(this).dialog('close'); },
            OK: function() {
              $('form', this).submit();
            }
          }
        });
      });
      return false;
    });
  });
</script>

app/views/breeze/blog/blogs/no_blog.html.erb
<% content_for :title, "Blog" %>

<%= pane_layout do |main| %>
  <% main.header do %>
    <h2></h2>
  <% end %>
  <% main.inner do %>
    <h1>You have no blogs set up.</h1>
    <%= form_tag admin_blog_setup_default_path do %>
      <p>
        <%= submit_tag "Click here", :class => :button %> to set up a new blog at <tt>/blog</tt>.
      </p>
    <% end %>
  <% end %>
<% end %>

<% content_for :left do %>
  <%= pane_layout do |left| %>
    <% left.header do %>
      <h2></h2>
    <% end %>
    <% left.inner do %>
 
    <% end %>
  <% end %>
<% end %>

<% content_for :right do -%>
  <%= pane_layout do |right| %>
    
  <% end %>
<% end -%>